### ISSUE TITLE
This project does not work with Pydantic<2.7.0

### ISSUE THREAD

**Issue by gerhardadler** [p2p-ld/numpydantic#36]
In Pydantic 2.7.0, `context` was added to `SerializationInfo`. (https://github.com/pydantic/pydantic-core/pull/1215)

This project uses this property in `serialization.jsonize_array`:
```py
def jsonize_array(value: Any, info: SerializationInfo) -> Union[list, dict]:
    """Use an interface class to render an array as JSON"""
    # perf: keys to skip in generation - anything named "value" is array data.
    skip = ["value"]

    interface_cls = Interface.match_output(value)
    array = interface_cls.to_json(value, info)
    if isinstance(array, JsonDict):
        array = array.model_dump(exclude_none=True)

    if info.context: # here
        if info.context.get("mark_interface", False):
            array = interface_cls.mark_json(array)

        if isinstance(array, list):
            return array
        ...
```

This does for example cause an exception when serializing dicts containing NDArrays:
```
pydantic_core._pydantic_core.PydanticSerializationError: Error calling function `jsonize_array`: AttributeError: 'pydantic_core._pydantic_core.SerializationInfo' object has no attribute 'context'
```

I suggest updating the dependencies to not allow older versions of Pydantic.

**Comment by sneakers-the-rat** [comment]
aha appreciate it :) will fix now
